projectFolder: "user"
projectName: "own-ktor-project"
buildType: 'Gradle'
group: "com.example"
version: "0.0.1-SNAPSHOT"
ktorVersion: "1.5.0"
kotlinVersion: "1.4.21"
port: "8080"
global:
  port: "8080"
